# Any values defined here are not used anywhere other than lint/CI.

elasticsearchHost: logs.example.com

# SSH subchart is currently enabled for CI.
#
# ssh:
#   enabled: false

api:
  replicaCount: 1
  image:
    tag: lagoon-core

keycloak:
  image:
    tag: lagoon-core

broker:
  replicaCount: 1

authServer:
  replicaCount: 1

webhooks2tasks:
  replicaCount: 1

webhookHandler:
  replicaCount: 1
