# Any values defined here are not used anywhere other than lint/CI.

# used in api
elasticsearchHost: logs.example.com

# used in ui
lagoonAPIURL: https://api.example.com/graphql
keycloakAPIURL: https://keycloak.example.com/auth

# SSH subchart is currently enabled for CI.
#
# ssh:
#   enabled: false

api:
  replicaCount: 1
  image:
    tag: lagoon-core

keycloak:
  image:
    tag: lagoon-core

broker:
  replicaCount: 1

authServer:
  replicaCount: 1

webhooks2tasks:
  replicaCount: 1

webhookHandler:
  replicaCount: 1

ui:
  replicaCount: 1

backupHandler:
  replicaCount: 1

autoIdler:
  image:
    tag: lagoon-core

storageCalculator:
  image:
    tag: lagoon-core

logs2slack:
  replicaCount: 1

logs2microsoftteams:
  replicaCount: 1

logs2rocketchat:
  replicaCount: 1

logs2email:
  replicaCount: 1

drushAlias:
  replicaCount: 1
