apiVersion: v2
name: lagoon-build-deploy
description:
  A Helm chart for Kubernetes which installs the Lagoon Remote controllers
  (https://github.com/uselagoon/remote-controller).
home: https://github.com/uselagoon/lagoon-charts
icon: https://raw.githubusercontent.com/uselagoon/lagoon-charts/main/icon.png
maintainers:
- name: shreddedbacon
  email: ben.jackson@amazee.io
  url: https://amazee.io
- name: smlx
  email: scott.leggett@amazee.io
  url: https://amazee.io

type: application

version: 0.7.5

appVersion: v0.1.15
