# Any values defined here are not used anywhere other than lint/CI.

apiDBHost: api-db
apiDBPassword: api-db
apiDBUser: api-db
apiHost: api
authServer: auth-server
jwtSecret: supersecret

ssh:
  replicaCount: 1
