{{/*
This somewhat complex logic is intended to:
  * generate a random secret value automatically on chart install
  * not overwrite the randomly generated value on upgrade
  * allow overriding if the value is explicitly defined
*/}}
{{- $data := index (lookup "v1" "Secret" .Release.Namespace (print (include "lagoon-core.api.fullname" . ) "-env")) "data" | default dict }}
{{- $apiDBPassword := coalesce .Values.apiDBPassword (ternary (randAlpha 32) (index $data "API_DB_PASSWORD" | default "" | b64dec) (index $data "API_DB_PASSWORD" | empty)) }}
{{- $harborAdminPassword := coalesce .Values.harborAdminPassword (ternary (randAlpha 32) (index $data "HARBOR_ADMIN_PASSWORD" | default "" | b64dec) (index $data "HARBOR_ADMIN_PASSWORD" | empty)) }}
{{- $jwtSecret := coalesce .Values.jwtSecret (ternary (randAlpha 32) (index $data "JWTSECRET" | default "" | b64dec) (index $data "JWTSECRET" | empty)) }}
{{- $logsDBAdminPassword := coalesce .Values.logsDBAdminPassword (ternary (randAlpha 32) (index $data "LOGSDB_ADMIN_PASSWORD" | default "" | b64dec) (index $data "LOGSDB_ADMIN_PASSWORD" | empty)) }}
{{- $rabbitMQPassword := coalesce .Values.rabbitMQPassword (ternary (randAlpha 32) (index $data "RABBITMQ_PASSWORD" | default "" | b64dec) (index $data "RABBITMQ_PASSWORD" | empty)) }}
{{- $redisPassword := coalesce .Values.redisPassword (ternary (randAlpha 32) (index $data "REDIS_PASSWORD" | default "" | b64dec) (index $data "REDIS_PASSWORD" | empty)) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lagoon-core.api.fullname" . }}-env
  labels:
    {{- include "lagoon-core.api.labels" . | nindent 4 }}
stringData:
  API_DB_PASSWORD: {{ $apiDBPassword | quote }}
  ELASTICSEARCH_HOST: {{ required "A valid .Values.elasticsearchHost required!" .Values.elasticsearchHost | quote }}
  HARBOR_ADMIN_PASSWORD: {{ $harborAdminPassword | quote }}
  JWTSECRET: {{ $jwtSecret | quote }}
  LOGSDB_ADMIN_PASSWORD: {{ $logsDBAdminPassword | quote }}
  RABBITMQ_PASSWORD: {{ $rabbitMQPassword | quote }}
  RABBITMQ_USERNAME: {{ required "A valid .Values.rabbitMQUsername required!" .Values.rabbitMQUsername | quote }}
  REDIS_PASSWORD: {{ $redisPassword | quote }}
