apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lagoon-core.api.fullname" . }}
  labels:
    {{- include "lagoon-core.api.labels" . | nindent 4 }}
spec:
{{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "lagoon-core.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/api.secret: {{ include (print $.Template.BasePath "/api.secret.yaml") . | sha256sum }}
        checksum/api-db.secret: {{ include (print $.Template.BasePath "/api-db.secret.yaml") . | sha256sum }}
        checksum/keycloak.secret: {{ include (print $.Template.BasePath "/keycloak.secret.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    {{- with .Values.api.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "lagoon-core.api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml (coalesce .Values.api.podSecurityContext .Values.podSecurityContext) | nindent 8 }}
      containers:
      - name: api
        securityContext:
          {{- toYaml .Values.api.securityContext | nindent 10 }}
        image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        env:
        - name: API_DB_HOST
          value: {{ include "lagoon-core.apiDB.fullname" . }}
        - name: REDIS_HOST
          value: {{ include "lagoon-core.apiRedis.fullname" . }}
        - name: RABBITMQ_HOST
          value: {{ include "lagoon-core.broker.fullname" . }}
        - name: API_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "lagoon-core.apiDB.fullname" . }}
              key: API_DB_PASSWORD
        - name: JWTSECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "lagoon-core.fullname" . }}-jwtsecret
              key: JWTSECRET
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "lagoon-core.keycloak.fullname" . }}
              key: KEYCLOAK_ADMIN_PASSWORD
        - name: KEYCLOAK_API_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "lagoon-core.keycloak.fullname" . }}
              key: KEYCLOAK_API_CLIENT_SECRET
        envFrom:
        - secretRef:
            name: {{ include "lagoon-core.api.fullname" . }}
        ports:
        - name: http-3000
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /status
            port: http-3000
          initialDelaySeconds: 150
        readinessProbe:
          httpGet:
            path: /status
            port: http-3000
        startupProbe:
          httpGet:
            path: /status
            port: http-3000
          failureThreshold: 20
          periodSeconds: 20
        resources:
          {{- toYaml .Values.api.resources | nindent 12 }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - {{ include "lagoon-core.name" . }}
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - {{ include "lagoon-core.api.fullname" . }}
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: kubernetes.io/hostname
      {{- with .Values.api.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
