{{- if .Values.api.ingress.enabled -}}
{{- $fullName := include "lagoon-core.api.fullname" . -}}
{{- $svcPort := .Values.api.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "lagoon-core.api.labels" . | nindent 4 }}
  annotations:
    acme.cert-manager.io/http01-ingress-class: {{coalesce .Values.api.ingress.ingressClassName .Values.defaultIngressClassName "not-set" }}
    {{- with .Values.api.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if or (.Values.api.ingress.ingressClassName) (.Values.defaultIngressClassName) }}
  ingressClassName: {{coalesce .Values.api.ingress.ingressClassName .Values.defaultIngressClassName }}
  {{- end }}
  {{- if .Values.api.ingress.tls }}
  tls:
    {{- range .Values.api.ingress.tls }}
  - hosts:
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
    secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.api.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ . }}
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ $svcPort }}
      {{- end }}
  {{- end }}
{{- end }}
