apiVersion: v1
kind: Service
metadata:
  name: {{ include "lagoon-core.broker.fullname" . }}-headless
  labels:
    {{- include "lagoon-core.broker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.broker.service.type }}
  ports:
  - port: {{ .Values.broker.service.ports.epmd }}
    targetPort: epmd
    name: epmd
  - port: {{ .Values.broker.service.ports.amqp }}
    targetPort: amqp
    name: amqp
  - port: {{ .Values.broker.service.ports.http }}
    targetPort: http
    name: http
  clusterIP: None
  selector:
    {{- include "lagoon-core.broker.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lagoon-core.broker.fullname" . }}
  labels:
    {{- include "lagoon-core.broker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.broker.service.type }}
  ports:
  - port: {{ .Values.broker.service.ports.epmd }}
    targetPort: epmd
    name: epmd
  - port: {{ .Values.broker.service.ports.amqp }}
    targetPort: amqp
    name: amqp
  - port: {{ .Values.broker.service.ports.http }}
    targetPort: http
    name: http
  selector:
    {{- include "lagoon-core.broker.selectorLabels" . | nindent 4 }}
