{{- if .Values.dioscuri.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "lagoon-remote.dioscuri.fullname" . }}-manager
  labels:
    {{- include "lagoon-remote.dioscuri.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "lagoon-remote.dioscuri.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: {{ include "lagoon-remote.dioscuri.fullname" . }}-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "lagoon-remote.dioscuri.fullname" . }}-proxy
  labels:
    {{- include "lagoon-remote.dioscuri.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "lagoon-remote.dioscuri.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: {{ include "lagoon-remote.dioscuri.fullname" . }}-proxy
  apiGroup: rbac.authorization.k8s.io
{{- end }}
