{{- if .Values.dioscuri.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "lagoon-remote.dioscuri.fullname" . }}-leader-election
  labels:
    {{- include "lagoon-remote.dioscuri.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "lagoon-remote.dioscuri.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "lagoon-remote.dioscuri.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
