{{- if .Values.dioscuri.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lagoon-remote.dioscuri.serviceAccountName" . }}
  labels:
    {{- include "lagoon-remote.dioscuri.labels" . | nindent 4 }}
  {{- with .Values.dioscuri.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
