{{- if .Values.insightsRemote.enabled -}}
{{- if .Values.insightsRemote.rabbitMQPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lagoon-remote.insightsRemote.fullname" . }}-rabbitmqsecret
type: kubernetes.io/basic-auth
stringData:
  username: {{ required "A valid .Values.insightsRemote.rabbitMQUsername required!" .Values.insightsRemote.rabbitMQUsername | quote }}
  password: {{ required "A valid .Values.insightsRemote.rabbitMQPassword required!" .Values.insightsRemote.rabbitMQPassword | quote }}
{{- end }}
{{- end }}