apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lagoon-remote.lagoonBuildDeploy.fullname" . }}
  labels:
    {{- include "lagoon-remote.lagoonBuildDeploy.labels" . | nindent 4 }}
stringData:
  RABBITMQ_PASSWORD: {{ required "A valid .Values.rabbitMQPassword required!" .Values.rabbitMQPassword | quote }}
  RABBITMQ_USERNAME: {{ required "A valid .Values.rabbitMQUsername required!" .Values.rabbitMQUsername | quote }}
