{{- if .Values.lagoonBuildDeploy.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lagoon-remote.lagoonBuildDeploy.fullname" . }}
  labels:
    {{- include "lagoon-remote.lagoonBuildDeploy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.lagoonBuildDeploy.service.type }}
  ports:
  - port: {{ .Values.lagoonBuildDeploy.service.port }}
    targetPort: https
    protocol: TCP
    name: https
  selector:
    {{- include "lagoon-remote.lagoonBuildDeploy.selectorLabels" . | nindent 4 }}
{{- end }}
