{{- if .Values.lagoonBuildDeploy.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lagoon-remote.lagoonBuildDeploy.fullname" . }}
  labels:
    {{- include "lagoon-remote.lagoonBuildDeploy.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "lagoon-remote.lagoonBuildDeploy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lagoon-remote.lagoonBuildDeploy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lagoon-remote.lagoonBuildDeploy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.lagoonBuildDeploy.podSecurityContext | nindent 8 }}
      containers:
      - name: kube-rbac-proxy
        image: "{{ .Values.kubeRBACProxy.image.repository }}:{{ .Values.kubeRBACProxy.image.tag }}"
        imagePullPolicy: {{ .Values.kubeRBACProxy.image.pullPolicy }}
        args:
        - "--secure-listen-address=0.0.0.0:8443"
        - "--upstream=http://127.0.0.1:8080/"
        - "--logtostderr=true"
        - "--v=10"
        ports:
        - containerPort: 8443
          name: https
      - name: manager
        image: "{{ .Values.lagoonBuildDeploy.image.repository }}:{{ .Values.lagoonBuildDeploy.image.tag | default .Chart.AppVersion}}"
        imagePullPolicy: {{ .Values.lagoonBuildDeploy.image.pullPolicy }}
        command:
        - /manager
        {{- with .Values.lagoonBuildDeploy.extraArgs }}
        args:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
        - name: LAGOON_TARGET_NAME
          value: {{ required "A valid .Values.lagoonTargetName required!" .Values.lagoonTargetName | quote }}
        - name: PENDING_MESSAGE_CRON
          value: {{ .Values.pendingMessageCron | quote }}
        - name: RABBITMQ_HOSTNAME
          value: {{ required "A valid .Values.rabbitMQHostname required!" .Values.rabbitMQHostname | quote }}
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "lagoon-remote.lagoonBuildDeploy.fullname" . }}
              key: RABBITMQ_PASSWORD
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "lagoon-remote.lagoonBuildDeploy.fullname" . }}
              key: RABBITMQ_USERNAME
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
