apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "lagoon-remote.storageCalculator.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "lagoon-remote.storageCalculator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "lagoon-remote.storageCalculator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "lagoon-remote.storageCalculator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
