apiVersion: v2
name: lagoon-test
description: A Helm chart for Kubernetes which runs the Lagoon test suite.
home: https://github.com/uselagoon/lagoon-charts
icon: https://raw.githubusercontent.com/uselagoon/lagoon-charts/main/icon.png
maintainers:
- name: smlx
  email: scott.leggett@amazee.io
  url: https://amazee.io
kubeVersion: ">= 1.21.0-0"

type: application

version: 0.42.0

appVersion: v2.10.0

# This section is used to collect a changelog for artifacthub.io
# It should be started afresh for each release
# Valid supported kinds are added, changed, deprecated, removed, fixed and security
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: added services test and deprecated old tests
    - kind: changed
      description: introduced minimum kubernetes version 1.21
    - kind: changed
      description: Use new startup probe on api-data-watcher-pusher.
