lagoon-build-deploy:
  enabled: true
  rabbitMQUsername: lagoon
  rabbitMQPassword: ci
  rabbitMQHostname: lagoon-core-broker
  lagoonTargetName: ci-local-control-k8s

dockerHost:
  image:
    repository: testlagoon/docker-host
  storage:
    size: 50Gi

imageTag: main

dbaasOperator:
  enabled: true
