apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "lagoon-core.api.fullname" . }}
  labels:
    {{- include "lagoon-core.api.labels" . | nindent 4 }}
stringData:
  REDIS_PASSWORD: {{ $redisPassword | quote }}
  LOGSDB_ADMIN_PASSWORD: {{ $logsDBAdminPassword | quote }}
  HARBOR_ADMIN_PASSWORD: {{ required "A valid .Values.harborAdminPassword required!" .Values.harborAdminPassword | quote }}
  S3_FILES_ACCESS_KEY_ID: {{ required "A valid .Values.s3FilesAccessKeyID required!" .Values.s3FilesAccessKeyID | quote }}
  S3_FILES_SECRET_ACCESS_KEY: {{ required "A valid .Values.s3FilesSecretAccessKey required!" .Values.s3FilesSecretAccessKey | quote }}
  S3_BAAS_ACCESS_KEY_ID: {{ required "A valid .Values.s3BAASAccessKeyID required!" .Values.s3BAASAccessKeyID | quote }}
  S3_BAAS_SECRET_ACCESS_KEY: {{ required "A valid .Values.s3BAASSecretAccessKey required!" .Values.s3BAASSecretAccessKey | quote }}
  {{- with .Values.gitlabAPIToken }}
  GITLAB_API_TOKEN: {{ . | quote }}
  {{- end }}
