apiVersion: v2
name: lagoon-ssh
description: >
  A Helm chart for Kubernetes which installs the lagoon ssh service.
home: https://github.com/amazeeio/charts
icon: https://raw.githubusercontent.com/amazeeio/charts/master/amazeeio_icon.png
maintainers:
- name: vincenzodnp
  email: vincenzo@amazee.io
  url: https://amazee.io
- name: smlx
  email: scott.leggett@amazee.io
  url: https://amazee.io

# Application charts are a collection of templates that can be packaged into
# versioned archives to be deployed.
type: application

# This is the chart version. This version number should be incremented each
# time you make changes to the chart and its templates, including the app
# version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.1

# This is the version number of the application being deployed. This version
# number should be incremented each time you make changes to the application.
# Versions are not expected to follow Semantic Versioning. They should reflect
# the version the application is using.
appVersion: v1-8-2
