apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ssh.fullname" . }}
  labels:
    {{- include "ssh.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ssh.replicaCount }}
  selector:
    matchLabels:
      {{- include "ssh.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/ssh.secret: {{ include (print $.Template.BasePath "/ssh.secret.yaml") . | sha256sum }}
      labels:
        {{- include "ssh.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.ssh.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.ssh.image.repository }}:{{ .Values.ssh.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.ssh.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: {{ include "ssh.fullname" . }}
        env:
        {{- if not .Values.apiDBPassword }}
        - name: API_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ required "Either .Values.apiDBPassword or .Values.apiDBPasswordSecret must be provided" .Values.apiDBPasswordSecret }}
              key: {{ .Values.apiDBPasswordKey }}
        {{- end }}
        {{- if not .Values.jwtSecret }}
        - name: JWTSECRET
          valueFrom:
            secretKeyRef:
              name: {{ required "Either .Values.jwtSecret or .Values.jwtSecretSecret must be provided" .Values.jwtSecretSecret }}
              key: {{ .Values.jwtSecretKey }}
        {{- end }}
        ports:
        - name: ssh
          containerPort: 2020
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: ssh
        readinessProbe:
          tcpSocket:
            port: ssh
        resources:
          {{- toYaml .Values.ssh.resources | nindent 12 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - {{ include "ssh.name" . }}
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: kubernetes.io/hostname
