apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{include "ssh.fullname" . }}
  labels:
    {{- include "ssh.labels" . | nindent 4 }}
stringData:
  API_DB_HOST: {{ required "A valid .Values.apiDBHost required!" .Values.apiDBHost | quote }}
  API_DB_USER: {{ required "A valid .Values.apiDBUser required!" .Values.apiDBUser | quote }}
  AUTH_SERVER: {{ required "A valid .Values.authServer required!" .Values.authServer | quote }}
  API_HOST: {{ required "A valid .Values.apiHost required!" .Values.apiHost | quote }}
{{- if .Values.apiDBPassword }}
  API_DB_PASSWORD: {{ .Values.apiDBPassword | quote }}
{{- end }}
{{- if .Values.jwtSecret }}
  JWTSECRET: {{ .Values.jwtSecret | quote }}
{{- end }}
