apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssh.fullname" . }}
  labels:
    {{- include "ssh.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ssh.service.type }}
  ports:
    - port: {{ .Values.ssh.service.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "ssh.selectorLabels" . | nindent 4 }}
